
services:
  book_review:
    container_name: book_review
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    ports:
      - "8000:8000"
    environment:
      - PG_USER=satti
      - PG_PASSWORD=admin123
      - PG_DB=book_management
      - PG_HOST=db
      - PG_PORT=5432
    depends_on:
      - db
  db:
    container_name: db
    image: postgres:13
    environment:
      - POSTGRES_USER=satti
      - POSTGRES_PASSWORD=admin123
      - POSTGRES_DB=book_management
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: {}