
services:
  book_review:
    container_name: book_review
    build: .
    command: ["daphne", "-b", "0.0.0.0", "-p", "8000", "book_review.asgi:application"]
    ports:
      - "8000:8000"
    environment:
      - PG_USER=satti
      - PG_PASSWORD=admin123
      - PG_DB=book_management
      - PG_HOST=db
      - PG_PORT=5432
    depends_on:
      - db
  db:
    container_name: db
    image: postgres:12
    environment:
      - POSTGRES_USER=satti
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=book_management
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: {}