# Generated by Django 5.1.5 on 2025-01-29 07:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0002_user_is_verified'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='book',
        ),
        migrations.RemoveField(
            model_name='review',
            name='user',
        ),
        migrations.DeleteModel(
            name='Book',
        ),
        migrations.DeleteModel(
            name='Review',
        ),
    ]
